### ISSUE TITLE
Trying to use non-existing Book properties

### ISSUE THREAD

**Issue by cliftonfoster** [PacktPublishing/Mastering-Blazor-WebAssembly#1]
Though I have found many, many typos in this book so far, the biggest issue I have found so far is in Chapter 4 (page 96 & 97) where you code three non-existing Book class properties, Id, Description, and Price. The code will obviously not work without adding those to the Book class. This process was completely skipped or missed up to this point.

![image](https://github.com/user-attachments/assets/a51b2571-9c0a-4c34-bd62-221a41727ef2)

**Comment by aksoftware98** [comment]
Hi @cliftonfoster 

Thank you for referencing this issue. I apologize for the inconvenience you have with the typos and this issue. 
Regarding the missing properties, it seems it's something we will work on for the next edition to avoid such cases. The goal was to focus on the Blazor part and the rendering property values so that took priority over the additional properties added as a sample.
The GitHub repository has all the properties listed and I hope that could you help continue your reading journey. 
https://github.com/PacktPublishing/Mastering-Blazor-WebAssembly/blob/main/Chapter_04/BooksStore/Models/Book.cs

I hope you found what you have read so far and the remaining of the book useful, and we will work hard to make the next edition better.

Thank you!
